version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: conexion-animal-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: conexion_animal
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./backend/database:/database  # Monta la carpeta con el SQL

volumes:
  postgres-data: